version: '3.7'
services:
  spa:
    build:
      context: "./env/dev/spa"
    ports:
      - "${VUE_UI_PORT:-8090}:8000"
      - "${SPA_APP_PORT:-8091}:8080"
      - '3000:3000'
    volumes:
      - ./spa:/var/spa:${CACHING_OPTION:-cached}
      - ./env/prod/spa/dist:/var/spa/dist
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /var/spa
    command: "vue ui -H 0.0.0.0 -p 8000"

  api:
    container_name: 'api'
    build:
      context: "./env/dev/api"
    ports:
      - "${API_PORT:-8092}:3333"
    volumes:
      - type: bind
        source: ./api
        target: /var/www
      - type: bind
        source: ./api/uploads
        target: /usr/local/Exercicios
    # links:
      # - mongo
    working_dir: /var/www
    command: "npm run dev"
    depends_on:
      - rabbitmq
    

  corretor:
    build:
      context: "./env/dev/corretor"
    # depends_on:
      # - kafka
    volumes:
      - type: bind
        source: ./corretor
        target: /var/www
      - type: bind
        source: ./corretor/temp
        target: /usr/local/Exercicios
    # working_dir: /var/www
    command: "npm run dev"



  mongo:
    #image: mongo
    build: ./env/dev/mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: correctiontool
    volumes:
      - mongodata:/data/db #Helps to store MongoDB data in `./mongo/data`
      #- ./env/dev/mongo/seed.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      #- ./env/dev/mongo/seed.js:/docker-entrypoint-initdb.d/seed.js:ro
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8094:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo


  mail:
    image: bytemark/smtp
    restart: always
    environment:
      RELAY_HOST: smtp.joaocastilho.com.br
      RELAY_PORT: 587
      RELAY_USERNAME: noreply@joaocastilho.com.br
      RELAY_PASSWORD: /lo@der.js:1085:14




  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user1234
      RABBITMQ_DEFAULT_PASS: user1234
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    # networks:
      # - rabbitmq_go_net


volumes:
  mongodata:
  composer-volume:

networks:
  rabbitmq_go_net:
    driver: bridge