version: '3.5'
services:
  spa:
    build:
      context: "./env/dev/spa"
    ports:
      - "${VUE_UI_PORT:-8090}:8000"
      - "${SPA_APP_PORT:-8091}:8080"
      - '3000:3000'
    volumes:
      - ./spa:/var/spa:${CACHING_OPTION:-cached}
      - ./env/prod/spa/dist:/var/spa/dist
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /var/spa
    command: "vue ui -H 0.0.0.0 -p 8000"

  api:
    build:
      context: "./env/dev/api"
    ports:
      - "${API_PORT:-8092}:3333"
    volumes:
      - ./api:/var/www
    links:
      - mongo
    working_dir: /var/www
    command: "npm run dev"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8094:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example


volumes:
  database-volume:
  composer-volume:
